/*
 * motoview_ffi.h — the hand-written C ABI for the MotoView native client core.
 *
 * This header is the Swift/C contract for the Rust crate `client/` built with
 * `--features ffi` (see client/src/ffi.rs). It is NOT generated by UniFFI:
 * uniffi-bindgen is not available on the build machine, so per the lead's
 * approval we ship a flat cbindgen-style C ABI and decode the JSON envelopes on
 * the Swift side with Foundation's JSONDecoder. This header is hand-maintained
 * to mirror the `#[no_mangle] pub extern "C"` signatures in ffi.rs exactly.
 *
 * Memory contract: every char* RETURNED by an mv_ffi_* function is owned by the
 * caller and MUST be released with mv_ffi_string_free(). Incoming char* are
 * borrowed (NUL-terminated UTF-8) and copied by Rust before return.
 */
#ifndef MOTOVIEW_FFI_H
#define MOTOVIEW_FFI_H

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Free a C string returned by any mv_ffi_* function. Null-safe. */
void mv_ffi_string_free(char *ptr);

/*
 * Parse a JSON IR forest (the Ir.mo.toJsonForest wire format) and return a
 * canonical, validated forest JSON inside an {"ok":true,"value":[...]} envelope,
 * or {"ok":false,"error":"..."} on failure. Caller frees the result.
 */
char *mv_ffi_parse_forest(const char *json);

/* Parse a single JSON IR node; same envelope shape. Caller frees the result. */
char *mv_ffi_parse_node(const char *json);

/*
 * Render a JSON IR forest to HTML (for the raw/WebView fallback container and
 * debugging). Returns {"ok":true,"value":"<html>"} or an error envelope.
 */
char *mv_ffi_render_forest(const char *json);

/*
 * Diff two JSON IR forests with the same keyed-reconcile/LIS the web brain uses.
 * Returns {"ok":true,"value":{"plan":"full"}} or
 * {"ok":true,"value":{"plan":"patch","ops":[...]}}. Caller frees the result.
 */
char *mv_ffi_ir_diff(const char *old_json, const char *new_json);

/*
 * Verify an IC response against the PINNED NNS root key (mainnet) — the
 * chain-key verifier (cert_verify::verify_response): tree-hash reconstruction,
 * delegation chain, BLS signature, range check, certified_data == SHA256(body).
 *
 * Binary inputs are raw byte buffers (ptr/len), not C strings:
 *   cert      — CBOR-encoded Certificate
 *   canister  — canister-id principal bytes
 *   path      — certified-data tree path, length-prefixed segments:
 *               [u32_le seg_len][seg bytes] ...  (empty buffer = empty path)
 *   body      — the response body whose SHA-256 must equal the certified leaf
 *   now_ns    — current time in ns, split into hi/lo u64 halves (no u128 in C)
 *   max_offset_ns — freshness window; 0 means use the 5-minute default
 *
 * Returns {"ok":true,"value":{"time_ns":"<u128 as string>"}} on success, or
 * {"ok":false,"error":"<CertError variant>"} on any failure (fails closed).
 * Caller frees the result. Root key is ALWAYS Mainnet — no downgrade possible.
 */
char *mv_ffi_verify_response(const uint8_t *cert_ptr, size_t cert_len,
                             const uint8_t *canister_ptr, size_t canister_len,
                             const uint8_t *path_ptr, size_t path_len,
                             const uint8_t *body_ptr, size_t body_len,
                             uint64_t now_ns_hi, uint64_t now_ns_lo,
                             uint64_t max_offset_ns);

#ifdef __cplusplus
}
#endif

#endif /* MOTOVIEW_FFI_H */
