//! Native (SwiftUI / Jetpack Compose) emitters for the `@theme brand="#hex"`
//! design tokens.
//!
//! The web target emits the brand ramp + alias tokens as CSS custom properties
//! via [`crate::color::brand_theme_css`]. The native clients need the SAME
//! tokens as native color objects so theming is PIXEL-IDENTICAL across
//! web / iOS / Android.
//!
//! To guarantee parity, these emitters reuse the EXACT same shade source as the
//! CSS emitter — they call [`crate::color::brand_ramp`] for the 16 ramp shades,
//! select alias shades through the IDENTICAL [`crate::color::BRAND_ALIASES`]
//! table and [`crate::color::shade_idx`] mapping. The mapping is NOT forked: a
//! native token for shade N is derived from the same `ramp[i]` hex the CSS
//! `--colorBrand…` custom property uses.

use crate::color::{brand_ramp, parse_hex, shade_idx, BRAND_ALIASES};

/// Parse a `#rrggbb` hex (or `#rgb`) into an 8-bit `(r, g, b)` triple, using the
/// SAME parser the CSS path uses, then quantizing to channels. This is the
/// single point where a ramp/alias hex becomes concrete native channels, so web
/// and native cannot diverge by rounding.
fn hex_to_rgb8(hex: &str) -> (u8, u8, u8) {
    let (r, g, b) = parse_hex(hex).expect("ramp/alias hex must be valid #rrggbb");
    let q = |v: f64| (v * 255.0).round().clamp(0.0, 255.0) as u8;
    (q(r), q(g), q(b))
}

/// Emit a SwiftUI source string defining the SAME tokens
/// [`crate::color::brand_theme_css`] emits, as `Color` values.
///
/// Layout:
///   * `enum BrandRamp` — the 16 raw ramp shades `colorBrandBackground{N}`
///     (N in 10..=160), each a `Color(.sRGB, red:green:blue:opacity:)`.
///   * `struct BrandTokens` — one field per alias token. A `light` and a `dark`
///     instance hold the alias values for each scheme, mirroring the CSS
///     `:root` (light) and `[data-theme="dark"]` (dark) blocks.
///   * `static func tokens(_ scheme: ColorScheme) -> BrandTokens` — picks the
///     scheme-appropriate instance, the native equivalent of
///     `@media (prefers-color-scheme: dark)`.
pub fn brand_theme_swift(hex: &str) -> Option<String> {
    let ramp = brand_ramp(hex)?;
    let mut out = String::new();

    out.push_str("import SwiftUI\n\n");
    out.push_str("// Generated by MotoView @theme brand=\"");
    out.push_str(hex);
    out.push_str("\". Mirrors brand_theme_css token-for-token.\n\n");

    // Raw ramp shades (scheme-independent), 10..=160.
    out.push_str("enum BrandRamp {\n");
    for i in 0..16 {
        let (r, g, b) = hex_to_rgb8(&ramp[i]);
        out.push_str(&format!(
            "    static let colorBrandBackground{}: Color = {}\n",
            (i + 1) * 10,
            swift_color(r, g, b),
        ));
    }
    out.push_str("}\n\n");

    // Alias tokens, light + dark, sharing BRAND_ALIASES + shade_idx with CSS.
    out.push_str("struct BrandTokens {\n");
    for (tok, _light, _dark) in BRAND_ALIASES {
        out.push_str(&format!("    let {}: Color\n", tok));
    }
    out.push('\n');

    out.push_str("    static let light = BrandTokens(\n");
    push_swift_alias_init(&mut out, &ramp, true);
    out.push_str("    )\n\n");

    out.push_str("    static let dark = BrandTokens(\n");
    push_swift_alias_init(&mut out, &ramp, false);
    out.push_str("    )\n\n");

    out.push_str("    static func tokens(_ scheme: ColorScheme) -> BrandTokens {\n");
    out.push_str("        scheme == .dark ? .dark : .light\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    Some(out)
}

fn push_swift_alias_init(out: &mut String, ramp: &[String; 16], light: bool) {
    let last = BRAND_ALIASES.len() - 1;
    for (n, (tok, l, d)) in BRAND_ALIASES.iter().enumerate() {
        let shade = if light { *l } else { *d };
        let (r, g, b) = hex_to_rgb8(&ramp[shade_idx(shade)]);
        out.push_str(&format!(
            "        {}: {}{}\n",
            tok,
            swift_color(r, g, b),
            if n == last { "" } else { "," },
        ));
    }
}

/// `Color(.sRGB, red:_, green:_, blue:_, opacity: 1)` with channels as the
/// exact 8-bit value divided by 255, so the float round-trips back to the same
/// channel.
fn swift_color(r: u8, g: u8, b: u8) -> String {
    format!(
        "Color(.sRGB, red: {}/255, green: {}/255, blue: {}/255, opacity: 1)",
        r, g, b
    )
}

/// Emit a Jetpack Compose source string defining the SAME tokens
/// [`crate::color::brand_theme_css`] emits, as `androidx.compose.ui.graphics.Color`
/// values.
///
/// Layout:
///   * `object BrandRamp` — the 16 raw ramp shades `colorBrandBackground{N}`,
///     each `Color(0xFFRRGGBB)`.
///   * `data class BrandTokens` + `LightBrandTokens` / `DarkBrandTokens` — one
///     property per alias token, the light/dark values mirroring the CSS
///     `:root` and `[data-theme="dark"]` blocks.
///   * `fun brandTokens(darkTheme: Boolean)` — picks the scheme instance.
pub fn brand_theme_kotlin(hex: &str) -> Option<String> {
    let ramp = brand_ramp(hex)?;
    let mut out = String::new();

    out.push_str("import androidx.compose.ui.graphics.Color\n\n");
    out.push_str("// Generated by MotoView @theme brand=\"");
    out.push_str(hex);
    out.push_str("\". Mirrors brand_theme_css token-for-token.\n\n");

    out.push_str("object BrandRamp {\n");
    for i in 0..16 {
        let (r, g, b) = hex_to_rgb8(&ramp[i]);
        out.push_str(&format!(
            "    val colorBrandBackground{} = {}\n",
            (i + 1) * 10,
            kotlin_color(r, g, b),
        ));
    }
    out.push_str("}\n\n");

    out.push_str("data class BrandTokens(\n");
    let last = BRAND_ALIASES.len() - 1;
    for (n, (tok, _l, _d)) in BRAND_ALIASES.iter().enumerate() {
        out.push_str(&format!(
            "    val {}: Color{}\n",
            tok,
            if n == last { "" } else { "," }
        ));
    }
    out.push_str(")\n\n");

    out.push_str("val LightBrandTokens = BrandTokens(\n");
    push_kotlin_alias_init(&mut out, &ramp, true);
    out.push_str(")\n\n");

    out.push_str("val DarkBrandTokens = BrandTokens(\n");
    push_kotlin_alias_init(&mut out, &ramp, false);
    out.push_str(")\n\n");

    out.push_str("fun brandTokens(darkTheme: Boolean): BrandTokens =\n");
    out.push_str("    if (darkTheme) DarkBrandTokens else LightBrandTokens\n");

    Some(out)
}

fn push_kotlin_alias_init(out: &mut String, ramp: &[String; 16], light: bool) {
    let last = BRAND_ALIASES.len() - 1;
    for (n, (tok, l, d)) in BRAND_ALIASES.iter().enumerate() {
        let shade = if light { *l } else { *d };
        let (r, g, b) = hex_to_rgb8(&ramp[shade_idx(shade)]);
        out.push_str(&format!(
            "    {} = {}{}\n",
            tok,
            kotlin_color(r, g, b),
            if n == last { "" } else { "," },
        ));
    }
}

/// `Color(0xFFRRGGBB)` — opaque ARGB literal.
fn kotlin_color(r: u8, g: u8, b: u8) -> String {
    format!("Color(0xFF{:02X}{:02X}{:02X})", r, g, b)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::color::{brand_ramp, brand_theme_css, shade_idx, BRAND_ALIASES};
    use std::collections::HashMap;

    /// The brand hexes under test: Fluent Communication blue, Fluent red, and a
    /// green so we cover three distinct hue families.
    const HEXES: &[&str] = &["#0f6cbd", "#d13438", "#107c10"];

    fn rgb8(hex: &str) -> (u8, u8, u8) {
        let (r, g, b) = parse_hex(hex).unwrap();
        let q = |v: f64| (v * 255.0).round().clamp(0.0, 255.0) as u8;
        (q(r), q(g), q(b))
    }

    /// Pull `r`,`g`,`b` channels out of a Swift `Color(.sRGB, red: R/255, ...)`
    /// literal.
    fn parse_swift_color(lit: &str) -> (u8, u8, u8) {
        let grab = |needle: &str| -> u8 {
            let start = lit.find(needle).unwrap_or_else(|| panic!("no {needle} in {lit}"))
                + needle.len();
            let rest = &lit[start..];
            let end = rest.find("/255").expect("expected /255");
            rest[..end].trim().parse().unwrap()
        };
        (grab("red: "), grab("green: "), grab("blue: "))
    }

    /// Pull `r`,`g`,`b` channels out of a Kotlin `Color(0xFFRRGGBB)` literal.
    fn parse_kotlin_color(lit: &str) -> (u8, u8, u8) {
        let start = lit.find("0xFF").expect("expected 0xFF") + 4;
        let hex = &lit[start..start + 6];
        let v = u32::from_str_radix(hex, 16).unwrap();
        (((v >> 16) & 0xff) as u8, ((v >> 8) & 0xff) as u8, (v & 0xff) as u8)
    }

    /// Map each `tok: <value>` (or `tok = <value>`) line to its trimmed RHS.
    fn collect_assignments(src: &str, sep: &str) -> HashMap<String, String> {
        let mut m = HashMap::new();
        for line in src.lines() {
            let line = line.trim().trim_end_matches(',');
            // Only field-assignment lines (skip `let x: Color` declarations,
            // which Swift writes as `tok: Color`).
            if let Some(idx) = line.find(sep) {
                let key = line[..idx].trim();
                let val = line[idx + sep.len()..].trim();
                if !key.is_empty()
                    && key.chars().all(|c| c.is_ascii_alphanumeric())
                    && val.starts_with("Color")
                {
                    m.insert(key.to_string(), val.to_string());
                }
            }
        }
        m
    }

    /// Parse the CSS `--token:#rrggbb;` declarations from a single CSS block
    /// (the inside of `:root{…}` or `[data-theme="dark"]{…}`).
    fn parse_css_block(block: &str) -> HashMap<String, (u8, u8, u8)> {
        let mut m = HashMap::new();
        for decl in block.split(';') {
            let decl = decl.trim();
            if let Some(rest) = decl.strip_prefix("--") {
                if let Some((tok, val)) = rest.split_once(':') {
                    if val.trim().starts_with('#') {
                        m.insert(tok.trim().to_string(), rgb8(val.trim()));
                    }
                }
            }
        }
        m
    }

    /// Split `brand_theme_css` output into (light :root block, dark block).
    fn css_blocks(css: &str) -> (HashMap<String, (u8, u8, u8)>, HashMap<String, (u8, u8, u8)>) {
        // light :root is the first `:root{…}`.
        let root_start = css.find(":root{").unwrap() + ":root{".len();
        let root_end = root_start + css[root_start..].find('}').unwrap();
        let light = parse_css_block(&css[root_start..root_end]);

        // dark is the `[data-theme="dark"]{…}` block.
        let dk = "[data-theme=\"dark\"]{";
        let dark_start = css.find(dk).unwrap() + dk.len();
        let dark_end = dark_start + css[dark_start..].find('}').unwrap();
        let dark = parse_css_block(&css[dark_start..dark_end]);
        (light, dark)
    }

    /// Every ramp shade N: Swift `Color(red:green:blue:)` channels and Kotlin
    /// `0xFF..` channels must both equal `ramp[i]`'s 8-bit RGB. Float channels
    /// must round-trip to the same 8-bit value.
    #[test]
    fn ramp_shades_match_swift_and_kotlin() {
        for hex in HEXES {
            let ramp = brand_ramp(hex).unwrap();
            let swift = brand_theme_swift(hex).unwrap();
            let kotlin = brand_theme_kotlin(hex).unwrap();

            for i in 0..16 {
                let n = (i + 1) * 10;
                let want = rgb8(&ramp[i]);

                let sw_line = swift
                    .lines()
                    .find(|l| l.contains(&format!("colorBrandBackground{}:", n)))
                    .unwrap_or_else(|| panic!("swift missing ramp {n} for {hex}"));
                assert_eq!(
                    parse_swift_color(sw_line),
                    want,
                    "swift ramp {n} != ramp[{i}] for {hex}"
                );

                let kt_line = kotlin
                    .lines()
                    .find(|l| l.contains(&format!("colorBrandBackground{} ", n)))
                    .unwrap_or_else(|| panic!("kotlin missing ramp {n} for {hex}"));
                assert_eq!(
                    parse_kotlin_color(kt_line),
                    want,
                    "kotlin ramp {n} != ramp[{i}] for {hex}"
                );

                // Float round-trip: r/255 * 255 rounds back to r.
                let (r, _, _) = want;
                assert_eq!(
                    ((r as f64 / 255.0) * 255.0).round() as u8,
                    r,
                    "channel {r} does not round-trip"
                );
            }
        }
    }

    /// PARITY PROOF: every alias token's Swift/Kotlin light value equals the CSS
    /// light value (same ramp shade), and dark equals the CSS dark value.
    /// Parsed straight out of `brand_theme_css` output and compared
    /// shade-for-shade.
    #[test]
    fn alias_tokens_match_css_light_and_dark() {
        for hex in HEXES {
            let css = brand_theme_css(hex).unwrap();
            let (css_light, css_dark) = css_blocks(&css);

            let swift = brand_theme_swift(hex).unwrap();
            let kotlin = brand_theme_kotlin(hex).unwrap();

            // Isolate the light/dark alias init bodies in each native source.
            let sw_light = slice_between(&swift, "static let light = BrandTokens(", "    )");
            let sw_dark = slice_between(&swift, "static let dark = BrandTokens(", "    )");

            let sw_light_map = collect_assignments(sw_light, ":");
            let sw_dark_map = collect_assignments(sw_dark, ":");

            let kt_light = slice_between(&kotlin, "val LightBrandTokens = BrandTokens(", "\n)");
            let kt_dark = slice_between(&kotlin, "val DarkBrandTokens = BrandTokens(", "\n)");
            let kt_light_map = collect_assignments(kt_light, "=");
            let kt_dark_map = collect_assignments(kt_dark, "=");

            for (tok, light_shade, dark_shade) in BRAND_ALIASES {
                let ramp = brand_ramp(hex).unwrap();
                let want_light = rgb8(&ramp[shade_idx(*light_shade)]);
                let want_dark = rgb8(&ramp[shade_idx(*dark_shade)]);

                // CSS itself uses the same shade — sanity-check the parse.
                assert_eq!(
                    css_light.get(*tok).copied(),
                    Some(want_light),
                    "css light {tok} for {hex}"
                );
                assert_eq!(
                    css_dark.get(*tok).copied(),
                    Some(want_dark),
                    "css dark {tok} for {hex}"
                );

                // Swift light/dark == CSS light/dark.
                assert_eq!(
                    parse_swift_color(sw_light_map.get(*tok).unwrap()),
                    css_light[*tok],
                    "swift light {tok} != css light for {hex}"
                );
                assert_eq!(
                    parse_swift_color(sw_dark_map.get(*tok).unwrap()),
                    css_dark[*tok],
                    "swift dark {tok} != css dark for {hex}"
                );

                // Kotlin light/dark == CSS light/dark.
                assert_eq!(
                    parse_kotlin_color(kt_light_map.get(*tok).unwrap()),
                    css_light[*tok],
                    "kotlin light {tok} != css light for {hex}"
                );
                assert_eq!(
                    parse_kotlin_color(kt_dark_map.get(*tok).unwrap()),
                    css_dark[*tok],
                    "kotlin dark {tok} != css dark for {hex}"
                );
            }
        }
    }

    /// Shade 80 (the brand input) must round-trip through both emitters.
    #[test]
    fn shade_80_round_trips_to_input() {
        for hex in HEXES {
            let want = rgb8(hex);

            let swift = brand_theme_swift(hex).unwrap();
            let sw_line = swift
                .lines()
                .find(|l| l.contains("colorBrandBackground80:"))
                .unwrap();
            assert_eq!(parse_swift_color(sw_line), want, "swift shade 80 != {hex}");

            let kotlin = brand_theme_kotlin(hex).unwrap();
            let kt_line = kotlin
                .lines()
                .find(|l| l.contains("colorBrandBackground80 "))
                .unwrap();
            assert_eq!(parse_kotlin_color(kt_line), want, "kotlin shade 80 != {hex}");
        }
    }

    #[test]
    fn invalid_hex_returns_none() {
        assert!(brand_theme_swift("not-a-color").is_none());
        assert!(brand_theme_kotlin("#12").is_none());
    }

    /// Return the substring strictly between `start` and the next `end` after it.
    fn slice_between<'a>(s: &'a str, start: &str, end: &str) -> &'a str {
        let a = s.find(start).unwrap_or_else(|| panic!("no {start:?}")) + start.len();
        let rest = &s[a..];
        let b = rest.find(end).unwrap_or_else(|| panic!("no {end:?} after {start:?}"));
        &rest[..b]
    }
}
