//! Project orchestration: discover `.mview` files, compile them, and assemble
//! a single Motoko actor (`src/main.mo`) that wires every page/layout into the
//! MotoView runtime.

use crate::ast::FileKind;
use crate::codegen::Codegen;
use crate::parser;
use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

pub struct BuildOptions {
    pub project_dir: PathBuf,
    pub app_name: String,
    pub out: PathBuf,
}

pub fn build(opts: &BuildOptions) -> Result<String, String> {
    let src = opts.project_dir.join("src");
    let pages_dir = src.join("Pages");
    let layouts_dir = src.join("Layouts");
    let components_dir = src.join("Components");

    let page_files = list_mview(&pages_dir);
    let layout_files = list_mview(&layouts_dir);
    let _component_files = list_mview(&components_dir);

    // Service/Model modules (real Motoko) are imported into the generated actor
    // so page @code can call them (e.g. `Crm.all()`, `Crm.Deal`).
    let mut extra_imports = String::new();
    for f in list_mo(&src.join("Services")) {
        let n = file_stem(&f);
        extra_imports.push_str(&format!("import {} \"Services/{}\";\n", n, n));
    }
    for f in list_mo(&src.join("Models")) {
        let n = file_stem(&f);
        extra_imports.push_str(&format!("import {} \"Models/{}\";\n", n, n));
    }

    if page_files.is_empty() {
        return Err(format!(
            "no .mview pages found in {}",
            pages_dir.display()
        ));
    }

    // Model type scanning is a roadmap feature; pass an empty registry for now.
    let models: HashMap<String, HashMap<String, String>> = HashMap::new();

    let mut page_objects = String::new();
    let mut page_records = String::new();
    let mut page_idents: Vec<String> = Vec::new();
    let mut routes: Vec<(String, String)> = Vec::new();

    for pf in &page_files {
        let name = file_stem(pf);
        let source = fs::read_to_string(pf).map_err(|e| format!("{}: {}", pf.display(), e))?;
        let file = parser::parse(&source, &name, FileKind::Page)?;
        let mut cg = Codegen::new(&models);
        let pg = cg.gen_page(&file);
        page_objects.push_str(&pg.object_block);
        page_objects.push('\n');
        page_records.push_str(&pg.page_record);
        page_idents.push(format!("{}Def", pg.name));
        routes.push((pg.route, pg.name));
    }

    let mut layout_funcs = String::new();
    let mut layout_entries: Vec<(String, String)> = Vec::new(); // (name, func)
    for lf in &layout_files {
        let name = file_stem(lf);
        let source = fs::read_to_string(lf).map_err(|e| format!("{}: {}", lf.display(), e))?;
        let file = parser::parse(&source, &name, FileKind::Layout)?;
        let mut cg = Codegen::new(&models);
        layout_funcs.push_str(&cg.gen_layout(&file));
        layout_funcs.push('\n');
        layout_entries.push((name.clone(), format!("mvLayout_{}", name)));
    }

    let secret = gen_secret(&opts.app_name);
    let main = assemble(
        &opts.app_name,
        &page_objects,
        &page_records,
        &page_idents,
        &layout_funcs,
        &layout_entries,
        &secret,
        &extra_imports,
    );

    if let Some(parent) = opts.out.parent() {
        let _ = fs::create_dir_all(parent);
    }
    fs::write(&opts.out, &main).map_err(|e| format!("writing {}: {}", opts.out.display(), e))?;

    let mut summary = format!(
        "compiled {} page(s), {} layout(s) -> {}\n",
        page_files.len(),
        layout_files.len(),
        opts.out.display()
    );
    summary.push_str("routes:\n");
    for (r, n) in &routes {
        summary.push_str(&format!("  {:<24} {}\n", r, n));
    }
    Ok(summary)
}

fn assemble(
    app_name: &str,
    page_objects: &str,
    page_records: &str,
    page_idents: &[String],
    layout_funcs: &str,
    layout_entries: &[(String, String)],
    secret: &str,
    extra_imports: &str,
) -> String {
    let pages_arr = page_idents.join(", ");
    let layouts_arr = layout_entries
        .iter()
        .map(|(n, f)| format!("{{ name = {:?}; render = {} }}", n, f))
        .collect::<Vec<_>>()
        .join(", ");

    format!(
        r#"// GENERATED by the MotoView compiler. Do not edit by hand.
// Edit the .mview files in src/Pages, src/Layouts and src/Components instead,
// then re-run `motoview build`.
import App "mo:motoview/App";
import Html "mo:motoview/Html";
import MV "mo:motoview/Types";
import Lib "mo:motoview";
import Nat "mo:base/Nat";
import Nat32 "mo:base/Nat32";
import Int "mo:base/Int";
import Float "mo:base/Float";
import Char "mo:base/Char";
import Text "mo:base/Text";
import Buffer "mo:base/Buffer";
{extra_imports}
actor {{
  // ---- conversion helpers used by generated event dispatch ----
  func mvNat(t : Text) : Nat {{
    var n : Nat = 0;
    for (c in t.chars()) {{
      let d = Char.toNat32(c);
      if (d >= 48 and d <= 57) {{ n := n * 10 + Nat32.toNat(d - 48) }};
    }};
    n;
  }};
  func mvInt(t : Text) : Int {{
    var n : Int = 0;
    var neg = false;
    for (c in t.chars()) {{
      if (c == '-') {{ neg := true }} else {{
        let d = Char.toNat32(c);
        if (d >= 48 and d <= 57) {{ n := n * 10 + Nat32.toNat(d - 48) }};
      }};
    }};
    if (neg) {{ -n }} else {{ n }};
  }};
  func mvIsEmail(t : Text) : Bool {{
    Text.contains(t, #char '@') and Text.contains(t, #char '.');
  }};
  func mvFormGet(ctx : MV.Ctx, k : Text) : ?Text {{
    for ((kk, vv) in ctx.form.vals()) {{ if (kk == k) {{ return ?vv }} }};
    null;
  }};

{page_objects}
{page_records}
{layout_funcs}

  let mvPages : [MV.Page] = [{pages_arr}];
  let mvLayouts : [MV.Layout] = [{layouts_arr}];
  let mvConfig : MV.Config = {{ appName = {app_name:?}; secret = {secret} : Blob; seo = true }};
  let mvApp = App.App(mvConfig, mvPages, mvLayouts, Lib.defaultAssets());

  public shared query (msg) func http_request(req : MV.HttpRequest) : async MV.HttpResponse {{
    mvApp.httpRequest(req, msg.caller);
  }};

  public shared (msg) func http_request_update(req : MV.HttpRequest) : async MV.HttpResponse {{
    mvApp.httpRequestUpdate(req, msg.caller);
  }};
}};
"#,
        app_name = app_name,
        page_objects = page_objects,
        page_records = page_records,
        layout_funcs = layout_funcs,
        pages_arr = pages_arr,
        layouts_arr = layouts_arr,
        secret = secret,
        extra_imports = extra_imports,
    )
}

/// Derive a 32-byte secret from the app name (MVP). Production apps should
/// install a random secret (raw_rand) into a stable variable.
fn gen_secret(app_name: &str) -> String {
    let mut state: u64 = 0xcbf29ce484222325;
    for b in app_name.bytes() {
        state ^= b as u64;
        state = state.wrapping_mul(0x100000001b3);
    }
    let mut out = String::from("\"");
    for _ in 0..32 {
        // xorshift64
        state ^= state << 13;
        state ^= state >> 7;
        state ^= state << 17;
        let byte = (state & 0xFF) as u8;
        out.push_str(&format!("\\{:02x}", byte));
    }
    out.push('"');
    out
}

fn list_mview(dir: &Path) -> Vec<PathBuf> {
    let mut out = Vec::new();
    collect_mview(dir, &mut out);
    out.sort();
    out
}

/// List top-level `.mo` files directly in `dir` (non-recursive).
fn list_mo(dir: &Path) -> Vec<PathBuf> {
    let mut out = Vec::new();
    if let Ok(entries) = fs::read_dir(dir) {
        for e in entries.flatten() {
            let p = e.path();
            if p.is_file() && p.extension().and_then(|s| s.to_str()) == Some("mo") {
                out.push(p);
            }
        }
    }
    out.sort();
    out
}

fn collect_mview(dir: &Path, out: &mut Vec<PathBuf>) {
    if let Ok(entries) = fs::read_dir(dir) {
        for e in entries.flatten() {
            let p = e.path();
            if p.is_dir() {
                collect_mview(&p, out);
            } else if p.extension().and_then(|s| s.to_str()) == Some("mview") {
                out.push(p);
            }
        }
    }
}

fn file_stem(p: &Path) -> String {
    p.file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or("Page")
        .to_string()
}
