import SwiftUI

// ============================================================================
// SLICE 7 TOKEN-THEMING HOOK.
//
// This file is the SwiftUI BrandTokens output the MotoView design-token
// cross-compiler emits at `<app>/.mvbuild/native/BrandTokens.swift` (Slice 7).
// It was copied VERBATIM from apps/bzzz/.mvbuild/native/BrandTokens.swift so the
// native renderer can use the SAME Fluent brand ramp the web build uses, token
// for token. In a real app build, the compiler drops this file straight into the
// app's Swift sources (or this package is regenerated per-brand) — see
// `Theme.swift` for how `NativeView` consumes it.
//
// Do not edit by hand; regenerate via the @theme directive.
// ============================================================================

// Generated by MotoView @theme brand="#0f6cbd". Mirrors brand_theme_css token-for-token.

enum BrandRamp {
    static let colorBrandBackground10: Color = Color(.sRGB, red: 6/255, green: 22/255, blue: 36/255, opacity: 1)
    static let colorBrandBackground20: Color = Color(.sRGB, red: 8/255, green: 34/255, blue: 56/255, opacity: 1)
    static let colorBrandBackground30: Color = Color(.sRGB, red: 10/255, green: 44/255, blue: 74/255, opacity: 1)
    static let colorBrandBackground40: Color = Color(.sRGB, red: 12/255, green: 56/255, blue: 94/255, opacity: 1)
    static let colorBrandBackground50: Color = Color(.sRGB, red: 14/255, green: 69/255, blue: 117/255, opacity: 1)
    static let colorBrandBackground60: Color = Color(.sRGB, red: 15/255, green: 82/255, blue: 140/255, opacity: 1)
    static let colorBrandBackground70: Color = Color(.sRGB, red: 17/255, green: 95/255, blue: 163/255, opacity: 1)
    static let colorBrandBackground80: Color = Color(.sRGB, red: 15/255, green: 108/255, blue: 189/255, opacity: 1)
    static let colorBrandBackground90: Color = Color(.sRGB, red: 40/255, green: 137/255, blue: 222/255, opacity: 1)
    static let colorBrandBackground100: Color = Color(.sRGB, red: 71/255, green: 164/255, blue: 245/255, opacity: 1)
    static let colorBrandBackground110: Color = Color(.sRGB, red: 98/255, green: 177/255, blue: 245/255, opacity: 1)
    static let colorBrandBackground120: Color = Color(.sRGB, red: 119/255, green: 187/255, blue: 247/255, opacity: 1)
    static let colorBrandBackground130: Color = Color(.sRGB, red: 150/255, green: 203/255, blue: 250/255, opacity: 1)
    static let colorBrandBackground140: Color = Color(.sRGB, red: 180/255, green: 217/255, blue: 250/255, opacity: 1)
    static let colorBrandBackground150: Color = Color(.sRGB, red: 207/255, green: 230/255, blue: 250/255, opacity: 1)
    static let colorBrandBackground160: Color = Color(.sRGB, red: 235/255, green: 244/255, blue: 252/255, opacity: 1)
}

struct BrandTokens {
    let colorBrandBackground: Color
    let colorBrandBackground2: Color
    let colorBrandBackground2Hover: Color
    let colorBrandBackground2Pressed: Color
    let colorBrandBackgroundHover: Color
    let colorBrandBackgroundPressed: Color
    let colorBrandBackgroundSelected: Color
    let colorBrandForeground1: Color
    let colorBrandForeground2: Color
    let colorBrandForegroundLink: Color
    let colorBrandForegroundLinkHover: Color
    let colorBrandForegroundLinkPressed: Color
    let colorBrandForegroundLinkSelected: Color
    let colorBrandStroke1: Color
    let colorBrandStroke2: Color
    let colorBrandStroke2Hover: Color
    let colorCompoundBrandBackground: Color
    let colorCompoundBrandBackgroundHover: Color
    let colorCompoundBrandBackgroundPressed: Color
    let colorCompoundBrandForeground1: Color
    let colorCompoundBrandForeground1Hover: Color
    let colorCompoundBrandForeground1Pressed: Color
    let colorCompoundBrandStroke: Color
    let colorCompoundBrandStrokeHover: Color
    let colorCompoundBrandStrokePressed: Color

    static let light = BrandTokens(
        colorBrandBackground: Color(.sRGB, red: 15/255, green: 108/255, blue: 189/255, opacity: 1),
        colorBrandBackground2: Color(.sRGB, red: 235/255, green: 244/255, blue: 252/255, opacity: 1),
        colorBrandBackground2Hover: Color(.sRGB, red: 207/255, green: 230/255, blue: 250/255, opacity: 1),
        colorBrandBackground2Pressed: Color(.sRGB, red: 150/255, green: 203/255, blue: 250/255, opacity: 1),
        colorBrandBackgroundHover: Color(.sRGB, red: 17/255, green: 95/255, blue: 163/255, opacity: 1),
        colorBrandBackgroundPressed: Color(.sRGB, red: 12/255, green: 56/255, blue: 94/255, opacity: 1),
        colorBrandBackgroundSelected: Color(.sRGB, red: 15/255, green: 82/255, blue: 140/255, opacity: 1),
        colorBrandForeground1: Color(.sRGB, red: 15/255, green: 108/255, blue: 189/255, opacity: 1),
        colorBrandForeground2: Color(.sRGB, red: 17/255, green: 95/255, blue: 163/255, opacity: 1),
        colorBrandForegroundLink: Color(.sRGB, red: 17/255, green: 95/255, blue: 163/255, opacity: 1),
        colorBrandForegroundLinkHover: Color(.sRGB, red: 15/255, green: 82/255, blue: 140/255, opacity: 1),
        colorBrandForegroundLinkPressed: Color(.sRGB, red: 12/255, green: 56/255, blue: 94/255, opacity: 1),
        colorBrandForegroundLinkSelected: Color(.sRGB, red: 17/255, green: 95/255, blue: 163/255, opacity: 1),
        colorBrandStroke1: Color(.sRGB, red: 15/255, green: 108/255, blue: 189/255, opacity: 1),
        colorBrandStroke2: Color(.sRGB, red: 180/255, green: 217/255, blue: 250/255, opacity: 1),
        colorBrandStroke2Hover: Color(.sRGB, red: 119/255, green: 187/255, blue: 247/255, opacity: 1),
        colorCompoundBrandBackground: Color(.sRGB, red: 15/255, green: 108/255, blue: 189/255, opacity: 1),
        colorCompoundBrandBackgroundHover: Color(.sRGB, red: 17/255, green: 95/255, blue: 163/255, opacity: 1),
        colorCompoundBrandBackgroundPressed: Color(.sRGB, red: 15/255, green: 82/255, blue: 140/255, opacity: 1),
        colorCompoundBrandForeground1: Color(.sRGB, red: 15/255, green: 108/255, blue: 189/255, opacity: 1),
        colorCompoundBrandForeground1Hover: Color(.sRGB, red: 17/255, green: 95/255, blue: 163/255, opacity: 1),
        colorCompoundBrandForeground1Pressed: Color(.sRGB, red: 15/255, green: 82/255, blue: 140/255, opacity: 1),
        colorCompoundBrandStroke: Color(.sRGB, red: 15/255, green: 108/255, blue: 189/255, opacity: 1),
        colorCompoundBrandStrokeHover: Color(.sRGB, red: 17/255, green: 95/255, blue: 163/255, opacity: 1),
        colorCompoundBrandStrokePressed: Color(.sRGB, red: 15/255, green: 82/255, blue: 140/255, opacity: 1)
    )

    static let dark = BrandTokens(
        colorBrandBackground: Color(.sRGB, red: 17/255, green: 95/255, blue: 163/255, opacity: 1),
        colorBrandBackground2: Color(.sRGB, red: 8/255, green: 34/255, blue: 56/255, opacity: 1),
        colorBrandBackground2Hover: Color(.sRGB, red: 6/255, green: 22/255, blue: 36/255, opacity: 1),
        colorBrandBackground2Pressed: Color(.sRGB, red: 150/255, green: 203/255, blue: 250/255, opacity: 1),
        colorBrandBackgroundHover: Color(.sRGB, red: 15/255, green: 108/255, blue: 189/255, opacity: 1),
        colorBrandBackgroundPressed: Color(.sRGB, red: 12/255, green: 56/255, blue: 94/255, opacity: 1),
        colorBrandBackgroundSelected: Color(.sRGB, red: 15/255, green: 82/255, blue: 140/255, opacity: 1),
        colorBrandForeground1: Color(.sRGB, red: 71/255, green: 164/255, blue: 245/255, opacity: 1),
        colorBrandForeground2: Color(.sRGB, red: 98/255, green: 177/255, blue: 245/255, opacity: 1),
        colorBrandForegroundLink: Color(.sRGB, red: 71/255, green: 164/255, blue: 245/255, opacity: 1),
        colorBrandForegroundLinkHover: Color(.sRGB, red: 98/255, green: 177/255, blue: 245/255, opacity: 1),
        colorBrandForegroundLinkPressed: Color(.sRGB, red: 40/255, green: 137/255, blue: 222/255, opacity: 1),
        colorBrandForegroundLinkSelected: Color(.sRGB, red: 17/255, green: 95/255, blue: 163/255, opacity: 1),
        colorBrandStroke1: Color(.sRGB, red: 71/255, green: 164/255, blue: 245/255, opacity: 1),
        colorBrandStroke2: Color(.sRGB, red: 14/255, green: 69/255, blue: 117/255, opacity: 1),
        colorBrandStroke2Hover: Color(.sRGB, red: 119/255, green: 187/255, blue: 247/255, opacity: 1),
        colorCompoundBrandBackground: Color(.sRGB, red: 71/255, green: 164/255, blue: 245/255, opacity: 1),
        colorCompoundBrandBackgroundHover: Color(.sRGB, red: 17/255, green: 95/255, blue: 163/255, opacity: 1),
        colorCompoundBrandBackgroundPressed: Color(.sRGB, red: 15/255, green: 82/255, blue: 140/255, opacity: 1),
        colorCompoundBrandForeground1: Color(.sRGB, red: 15/255, green: 108/255, blue: 189/255, opacity: 1),
        colorCompoundBrandForeground1Hover: Color(.sRGB, red: 17/255, green: 95/255, blue: 163/255, opacity: 1),
        colorCompoundBrandForeground1Pressed: Color(.sRGB, red: 15/255, green: 82/255, blue: 140/255, opacity: 1),
        colorCompoundBrandStroke: Color(.sRGB, red: 15/255, green: 108/255, blue: 189/255, opacity: 1),
        colorCompoundBrandStrokeHover: Color(.sRGB, red: 17/255, green: 95/255, blue: 163/255, opacity: 1),
        colorCompoundBrandStrokePressed: Color(.sRGB, red: 15/255, green: 82/255, blue: 140/255, opacity: 1)
    )

    static func tokens(_ scheme: ColorScheme) -> BrandTokens {
        scheme == .dark ? .dark : .light
    }
}
