#!/usr/bin/env bash
# Build the Rust→WASM client and embed it (plus the JS glue and CSS) into the
# Motoko runtime as `runtime/src/ClientAssets.mo`, so every MotoView canister
# can serve /motoview.wasm, /motoview.js and /motoview.css.
#
# Requires: cargo, the wasm32-unknown-unknown target, wasm-opt, base64, perl.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT/client"

echo "==> building client (release, wasm32)"
cargo build --release --target wasm32-unknown-unknown
RAW="target/wasm32-unknown-unknown/release/motoview_client.wasm"

mkdir -p dist
echo "==> optimizing with wasm-opt"
wasm-opt -Oz \
  --enable-bulk-memory \
  --enable-nontrapping-float-to-int \
  --enable-sign-ext \
  --enable-mutable-globals \
  "$RAW" -o dist/motoview.wasm
cp glue/motoview.js dist/motoview.js
cp glue/motoview.css dist/motoview.css
echo "    wasm: $(wc -c < dist/motoview.wasm) bytes"

# escape a file's contents into a single-line Motoko text literal body
escape_mo() {
  perl -0pe 's/\\/\\\\/g; s/"/\\"/g; s/\r//g; s/\n/\\n/g; s/\t/\\t/g' "$1"
}

WASM_B64="$(base64 < dist/motoview.wasm | tr -d '\n')"
JS_ESC="$(escape_mo glue/motoview.js)"
CSS_ESC="$(escape_mo glue/motoview.css)"

OUT="$ROOT/runtime/src/ClientAssets.mo"
echo "==> writing $OUT"
{
  cat <<'HEADER'
/// Static client assets served by every MotoView canister.
///
/// GENERATED by `tools/build-client.sh` — do not edit by hand. Holds the
/// Rust→WASM client (base64), its JS bootstrap/glue, and the base CSS.
import Types "Types";
import Base64 "Base64";

module {
HEADER
  printf '  let wasmB64 : Text = "%s";\n\n' "$WASM_B64"
  printf '  let clientJs : Text = "%s";\n\n' "$JS_ESC"
  printf '  let css : Text = "%s";\n\n' "$CSS_ESC"
  cat <<'FOOTER'
  let favicon : Text = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 32 32\"><rect width=\"32\" height=\"32\" rx=\"7\" fill=\"#6d28d9\"/><path d=\"M7 23V9l5 7 5-7v14\" fill=\"none\" stroke=\"#fff\" stroke-width=\"2.4\" stroke-linejoin=\"round\" stroke-linecap=\"round\"/><circle cx=\"23\" cy=\"12\" r=\"2.4\" fill=\"#fff\"/></svg>";

  public func assets() : Types.Assets {
    {
      clientJs;
      clientWasm = Base64.decode(wasmB64);
      css;
      favicon;
    };
  };
};
FOOTER
} > "$OUT"

echo "==> done"
